backend:
  name: git-gateway
  branch: main  # or 'master' if your repo uses that

media_folder: "images" # Where uploaded images will go (relative to root)
public_folder: "/images" # How they are accessed in the browser

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Published Date", name: "date", widget: "datetime" }
      - { label: "Genre", name: "genre", widget: "string" }
      - { label: "Time to Read", name: "readTime", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
